In [1]:
import pandas as pd

def midsquare(seed: int, n: int = 100):
  seed_str = str(seed)
  d = len(seed_str)
  x = seed

  data = []
  for i in range(1, n + 1):
    sq = x**2
    sq_str = str(sq).zfill(2 * d)
    start = (len(sq_str) - d) // 2
    x = int(sq_str[start : start + d])
    u = x / (10**d)
    data.append({"i": i, "X_i": x, "u_i": u})
  return pd.DataFrame(data), d

# Ejecución para las semillas del ejercicio
seeds = [1931, 675248, 4567, 12122, 7179345]
results = {}

for s in seeds:
  df, d = midsquare(s, n=100)
  results[s] = df
  print(f"== Semilla {s} (D={d}) ==")
  print(df.head(100).to_string(index=False))
  print("\n")

== Semilla 1931 (D=4) ==
  i  X_i    u_i
  1 7287 0.7287
  2 1003 0.1003
  3   60 0.0060
  4   36 0.0036
  5   12 0.0012
  6    1 0.0001
  7    0 0.0000
  8    0 0.0000
  9    0 0.0000
 10    0 0.0000
 11    0 0.0000
 12    0 0.0000
 13    0 0.0000
 14    0 0.0000
 15    0 0.0000
 16    0 0.0000
 17    0 0.0000
 18    0 0.0000
 19    0 0.0000
 20    0 0.0000
 21    0 0.0000
 22    0 0.0000
 23    0 0.0000
 24    0 0.0000
 25    0 0.0000
 26    0 0.0000
 27    0 0.0000
 28    0 0.0000
 29    0 0.0000
 30    0 0.0000
 31    0 0.0000
 32    0 0.0000
 33    0 0.0000
 34    0 0.0000
 35    0 0.0000
 36    0 0.0000
 37    0 0.0000
 38    0 0.0000
 39    0 0.0000
 40    0 0.0000
 41    0 0.0000
 42    0 0.0000
 43    0 0.0000
 44    0 0.0000
 45    0 0.0000
 46    0 0.0000
 47    0 0.0000
 48    0 0.0000
 49    0 0.0000
 50    0 0.0000
 51    0 0.0000
 52    0 0.0000
 53    0 0.0000
 54    0 0.0000
 55    0 0.0000
 56    0 0.0000
 57    0 0.0000
 58    0 0.0000
 59    0 0.0000
 60    0 0.0000
 61    0 0.0000
 62    0 0.0000
 63    0 0.0000
 64    0 0.0000
 65    0 0.0000
 66    0 0.0000
 67    0 0.0000
 68    0 0.0000
 69    0 0.0000
 70    0 0.0000
 71    0 0.0000
 72    0 0.0000
 73    0 0.0000
 74    0 0.0000
 75    0 0.0000
 76    0 0.0000
 77    0 0.0000
 78    0 0.0000
 79    0 0.0000
 80    0 0.0000
 81    0 0.0000
 82    0 0.0000
 83    0 0.0000
 84    0 0.0000
 85    0 0.0000
 86    0 0.0000
 87    0 0.0000
 88    0 0.0000
 89    0 0.0000
 90    0 0.0000
 91    0 0.0000
 92    0 0.0000
 93    0 0.0000
 94    0 0.0000
 95    0 0.0000
 96    0 0.0000
 97    0 0.0000
 98    0 0.0000
 99    0 0.0000
100    0 0.0000


== Semilla 675248 (D=6) ==
  i    X_i      u_i
  1 959861 0.959861
  2 333139 0.333139
  3 981593 0.981593
  4 524817 0.524817
  5 432883 0.432883
  6 387691 0.387691
  7 304311 0.304311
  8 605184 0.605184
  9 247673 0.247673
 10 341914 0.341914
 11 905183 0.905183
 12 356263 0.356263
 13 923325 0.923325
 14 529055 0.529055
 15 899193 0.899193
 16 548051 0.548051
 17 359898 0.359898
 18 526570 0.526570
 19 275964 0.275964
 20 156129 0.156129
 21 376264 0.376264
 22 574597 0.574597
 23 161712 0.161712
 24 150770 0.150770
 25 731592 0.731592
 26 226854 0.226854
 27 462737 0.462737
 28 125531 0.125531
 29 758031 0.758031
 30 610996 0.610996
 31 316112 0.316112
 32 926796 0.926796
 33 950825 0.950825
 34  68180 0.068180
 35 648512 0.648512
 36 567814 0.567814
 37 412738 0.412738
 38 352656 0.352656
 39 366254 0.366254
 40 141992 0.141992
 41 161728 0.161728
 42 155945 0.155945
 43 318843 0.318843
 44 660858 0.660858
 45 733296 0.733296
 46 723023 0.723023
 47 762258 0.762258
 48  37258 0.037258
 49 388158 0.388158
 50 666632 0.666632
 51 398223 0.398223
 52 581557 0.581557
 53 208544 0.208544
 54 490599 0.490599
 55 687378 0.687378
 56 488514 0.488514
 57 645928 0.645928
 58 222981 0.222981
 59 720526 0.720526
 60 157716 0.157716
 61 874336 0.874336
 62 463440 0.463440
 63 776633 0.776633
 64 158816 0.158816
 65 222521 0.222521
 66 515595 0.515595
 67 838204 0.838204
 68 585945 0.585945
 69 331543 0.331543
 70 920760 0.920760
 71 798977 0.798977
 72 364246 0.364246
 73 675148 0.675148
 74 824821 0.824821
 75 329682 0.329682
 76 690221 0.690221
 77 405028 0.405028
 78  47680 0.047680
 79 273382 0.273382
 80 737717 0.737717
 81 226372 0.226372
 82 244282 0.244282
 83 673695 0.673695
 84 864953 0.864953
 85 143692 0.143692
 86 647390 0.647390
 87 113812 0.113812
 88 953171 0.953171
 89 534955 0.534955
 90 176852 0.176852
 91 276629 0.276629
 92 523603 0.523603
 93 160101 0.160101
 94 632330 0.632330
 95 841228 0.841228
 96 664547 0.664547
 97 622715 0.622715
 98 773971 0.773971
 99  31108 0.031108
100 967707 0.967707


== Semilla 4567 (D=4) ==
  i  X_i    u_i
  1 8574 0.8574
  2 5134 0.5134
  3 3579 0.3579
  4 8092 0.8092
  5 4804 0.4804
  6  784 0.0784
  7 6146 0.6146
  8 7733 0.7733
  9 7992 0.7992
 10 8720 0.8720
 11  384 0.0384
 12 1474 0.1474
 13 1726 0.1726
 14 9790 0.9790
 15 8441 0.8441
 16 2504 0.2504
 17 2700 0.2700
 18 2900 0.2900
 19 4100 0.4100
 20 8100 0.8100
 21 6100 0.6100
 22 2100 0.2100
 23 4100 0.4100
 24 8100 0.8100
 25 6100 0.6100
 26 2100 0.2100
 27 4100 0.4100
 28 8100 0.8100
 29 6100 0.6100
 30 2100 0.2100
 31 4100 0.4100
 32 8100 0.8100
 33 6100 0.6100
 34 2100 0.2100
 35 4100 0.4100
 36 8100 0.8100
 37 6100 0.6100
 38 2100 0.2100
 39 4100 0.4100
 40 8100 0.8100
 41 6100 0.6100
 42 2100 0.2100
 43 4100 0.4100
 44 8100 0.8100
 45 6100 0.6100
 46 2100 0.2100
 47 4100 0.4100
 48 8100 0.8100
 49 6100 0.6100
 50 2100 0.2100
 51 4100 0.4100
 52 8100 0.8100
 53 6100 0.6100
 54 2100 0.2100
 55 4100 0.4100
 56 8100 0.8100
 57 6100 0.6100
 58 2100 0.2100
 59 4100 0.4100
 60 8100 0.8100
 61 6100 0.6100
 62 2100 0.2100
 63 4100 0.4100
 64 8100 0.8100
 65 6100 0.6100
 66 2100 0.2100
 67 4100 0.4100
 68 8100 0.8100
 69 6100 0.6100
 70 2100 0.2100
 71 4100 0.4100
 72 8100 0.8100
 73 6100 0.6100
 74 2100 0.2100
 75 4100 0.4100
 76 8100 0.8100
 77 6100 0.6100
 78 2100 0.2100
 79 4100 0.4100
 80 8100 0.8100
 81 6100 0.6100
 82 2100 0.2100
 83 4100 0.4100
 84 8100 0.8100
 85 6100 0.6100
 86 2100 0.2100
 87 4100 0.4100
 88 8100 0.8100
 89 6100 0.6100
 90 2100 0.2100
 91 4100 0.4100
 92 8100 0.8100
 93 6100 0.6100
 94 2100 0.2100
 95 4100 0.4100
 96 8100 0.8100
 97 6100 0.6100
 98 2100 0.2100
 99 4100 0.4100
100 8100 0.8100


== Semilla 12122 (D=5) ==
  i   X_i     u_i
  1 46942 0.46942
  2  3551 0.03551
  3 12609 0.12609
  4 58986 0.58986
  5 79348 0.79348
  6 96105 0.96105
  7 36171 0.36171
  8  8341 0.08341
  9 69572 0.69572
 10 40263 0.40263
 11 21109 0.21109
 12 45589 0.45589
 13 78356 0.78356
 14 39662 0.39662
 15 73074 0.73074
 16 39809 0.39809
 17 84756 0.84756
 18 83579 0.83579
 19 85449 0.85449
 20  1531 0.01531
 21  2343 0.02343
 22  5489 0.05489
 23 30129 0.30129
 24  7756 0.07756
 25 60155 0.60155
 26 18624 0.18624
 27 46853 0.46853
 28 95203 0.95203
 29 63611 0.63611
 30 46359 0.46359
 31 49156 0.49156
 32 16312 0.16312
 33 66081 0.66081
 34 66698 0.66698
 35 48623 0.48623
 36 64196 0.64196
 37 21126 0.21126
 38 46307 0.46307
 39 44338 0.44338
 40 65858 0.65858
 41 37276 0.37276
 42 89500 0.89500
 43 10250 0.10250
 44  5062 0.05062
 45 25623 0.25623
 46 56538 0.56538
 47 96545 0.96545
 48 20937 0.20937
 49 38357 0.38357
 50 71259 0.71259
 51 77845 0.77845
 52 59844 0.59844
 53 81304 0.81304
 54 10340 0.10340
 55  6915 0.06915
 56 47817 0.47817
 57 86465 0.86465
 58 76196 0.76196
 59  5830 0.05830
 60 33988 0.33988
 61 55184 0.55184
 62 45273 0.45273
 63 49644 0.49644
 64 64526 0.64526
 65 63604 0.63604
 66 45468 0.45468
 67 67339 0.67339
 68 34540 0.34540
 69 93011 0.93011
 70 51046 0.51046
 71  5694 0.05694
 72 32421 0.32421
 73 51121 0.51121
 74 13356 0.13356
 75 78382 0.78382
 76 43737 0.43737
 77 12925 0.12925
 78 67055 0.67055
 79 96373 0.96373
 80 87755 0.87755
 81   940 0.00940
 82   883 0.00883
 83   779 0.00779
 84   606 0.00606
 85   367 0.00367
 86   134 0.00134
 87    17 0.00017
 88     0 0.00000
 89     0 0.00000
 90     0 0.00000
 91     0 0.00000
 92     0 0.00000
 93     0 0.00000
 94     0 0.00000
 95     0 0.00000
 96     0 0.00000
 97     0 0.00000
 98     0 0.00000
 99     0 0.00000
100     0 0.00000


== Semilla 7179345 (D=7) ==
  i     X_i      u_i
  1 4299462 0.429946
  2 8537348 0.853735
  3 8631087 0.863109
  4 9566280 0.956628
  5 1371303 0.137130
  6 8047191 0.804719
  7 5728299 0.572830
  8 1340943 0.134094
  9 9812812 0.981281
 10 9127934 0.912793
 11 1917910 0.191791
 12 7837876 0.783788
 13 3230019 0.323002
 14 3302274 0.330227
 15  501357 0.050136
 16 5135884 0.513588
 17 7730446 0.773045
 18 5979535 0.597954
 19 5483881 0.548388
 20 7295082 0.729508
 21 1822138 0.182214
 22 2018689 0.201869
 23 7510527 0.751053
 24  801581 0.080158
 25 4253209 0.425321
 26 8978679 0.897868
 27 1667658 0.166766
 28 8108320 0.810832
 29 4485322 0.448532
 30 1811344 0.181134
 31 8096708 0.809671
 32 5668043 0.566804
 33 2671144 0.267114
 34 3501026 0.350103
 35 5718305 0.571831
 36 9901207 0.990121
 37 3390005 0.339000
 38 9213390 0.921339
 39 8655529 0.865553
 40 1818226 0.181823
 41  594578 0.059458
 42 5352299 0.535230
 43 4710458 0.471046
 44 8841456 0.884146
 45 7134419 0.713442
 46 9993446 0.999345
 47 6896295 0.689630
 48 5888472 0.588847
 49 7410249 0.741025
 50 1179024 0.117902
 51 9009759 0.900976
 52 7575723 0.757572
 53 9157897 0.915790
 54 6707746 0.670775
 55 9385640 0.938564
 56 9023820 0.902382
 57 2932739 0.293274
 58   95804 0.009580
 59  917840 0.091784
 60 4243026 0.424303
 61  326963 0.032696
 62  690480 0.069048
 63 7676263 0.767626
 64 2501364 0.250136
 65 5682186 0.568219
 66 8723773 0.872377
 67  421535 0.042154
 68 7769175 0.776918
 69 6008018 0.600802
 70 9628028 0.962803
 71 9892316 0.989232
 72 5791584 0.579158
 73 4244522 0.424452
 74 1596700 0.159670
 75 4945089 0.494509
 76 5390521 0.539052
 77 5771665 0.577167
 78 1211687 0.121169
 79 6818538 0.681854
 80 9246045 0.924605
 81 8934814 0.893481
 82 3090121 0.309012
 83 4884779 0.488478
 84 6106587 0.610659
 85 9040478 0.904048
 86 3024246 0.302425
 87 4606386 0.460639
 88 1879198 0.187920
 89 3138512 0.313851
 90 5025757 0.502576
 91 5823342 0.582334
 92 1131204 0.113120
 93 7962248 0.796225
 94 9739321 0.973932
 95 5437354 0.543735
 96 6481852 0.648185
 97 1440534 0.144053
 98 7513820 0.751382
 99 5749099 0.574910
100 5213931 0.521393

In [2]:
import numpy as np
import time
from datetime import datetime

def genran(a,c,m,xant):
    xsig = (a*xant + c) % m
    usig = xsig / m
    return [xsig,usig]

def genranN(a,c,m,x0,N):
    xant = x0
    I=[]
    X=[]
    U=[]
    for t in range(1, N+1):
        [xi,ui] = genran(a,c,m,xant)
        I.append(t)
        X.append(xi)
        U.append(ui)
        xant = xi
    return [I,X,U]

def showValues(I,X,U):
    print("i\tXi\tUi")
    for t in range(0, len(X)):
        print("%d\t%d\t%2.4f" % (I[t],X[t],U[t]), sep=' ', end='\n')

In [3]:
N = 100

a = 115
c = 0
m = 128
x0 = 127

[I,X,U] = genranN(a,c,m,x0,N)
showValues(I,X,U)

i	Xi	Ui
1	13	0.1016
2	87	0.6797
3	21	0.1641
4	111	0.8672
5	93	0.7266
6	71	0.5547
7	101	0.7891
8	95	0.7422
9	45	0.3516
10	55	0.4297
11	53	0.4141
12	79	0.6172
13	125	0.9766
14	39	0.3047
15	5	0.0391
16	63	0.4922
17	77	0.6016
18	23	0.1797
19	85	0.6641
20	47	0.3672
21	29	0.2266
22	7	0.0547
23	37	0.2891
24	31	0.2422
25	109	0.8516
26	119	0.9297
27	117	0.9141
28	15	0.1172
29	61	0.4766
30	103	0.8047
31	69	0.5391
32	127	0.9922
33	13	0.1016
34	87	0.6797
35	21	0.1641
36	111	0.8672
37	93	0.7266
38	71	0.5547
39	101	0.7891
40	95	0.7422
41	45	0.3516
42	55	0.4297
43	53	0.4141
44	79	0.6172
45	125	0.9766
46	39	0.3047
47	5	0.0391
48	63	0.4922
49	77	0.6016
50	23	0.1797
51	85	0.6641
52	47	0.3672
53	29	0.2266
54	7	0.0547
55	37	0.2891
56	31	0.2422
57	109	0.8516
58	119	0.9297
59	117	0.9141
60	15	0.1172
61	61	0.4766
62	103	0.8047
63	69	0.5391
64	127	0.9922
65	13	0.1016
66	87	0.6797
67	21	0.1641
68	111	0.8672
69	93	0.7266
70	71	0.5547
71	101	0.7891
72	95	0.7422
73	45	0.3516
74	55	0.4297
75	53	0.4141
76	79	0.6172
77	125	0.9766
78	39	0.3047
79	5	0.0391
80	63	0.4922
81	77	0.6016
82	23	0.1797
83	85	0.6641
84	47	0.3672
85	29	0.2266
86	7	0.0547
87	37	0.2891
88	31	0.2422
89	109	0.8516
90	119	0.9297
91	117	0.9141
92	15	0.1172
93	61	0.4766
94	103	0.8047
95	69	0.5391
96	127	0.9922
97	13	0.1016
98	87	0.6797
99	21	0.1641
100	111	0.8672

In [4]:
N = 100

a = 25
c = 5
m = 48
x0 = 43

[I,X,U] = genranN(a,c,m,x0,N)
showValues(I,X,U)

i	Xi	Ui
1	24	0.5000
2	29	0.6042
3	10	0.2083
4	15	0.3125
5	44	0.9167
6	1	0.0208
7	30	0.6250
8	35	0.7292
9	16	0.3333
10	21	0.4375
11	2	0.0417
12	7	0.1458
13	36	0.7500
14	41	0.8542
15	22	0.4583
16	27	0.5625
17	8	0.1667
18	13	0.2708
19	42	0.8750
20	47	0.9792
21	28	0.5833
22	33	0.6875
23	14	0.2917
24	19	0.3958
25	0	0.0000
26	5	0.1042
27	34	0.7083
28	39	0.8125
29	20	0.4167
30	25	0.5208
31	6	0.1250
32	11	0.2292
33	40	0.8333
34	45	0.9375
35	26	0.5417
36	31	0.6458
37	12	0.2500
38	17	0.3542
39	46	0.9583
40	3	0.0625
41	32	0.6667
42	37	0.7708
43	18	0.3750
44	23	0.4792
45	4	0.0833
46	9	0.1875
47	38	0.7917
48	43	0.8958
49	24	0.5000
50	29	0.6042
51	10	0.2083
52	15	0.3125
53	44	0.9167
54	1	0.0208
55	30	0.6250
56	35	0.7292
57	16	0.3333
58	21	0.4375
59	2	0.0417
60	7	0.1458
61	36	0.7500
62	41	0.8542
63	22	0.4583
64	27	0.5625
65	8	0.1667
66	13	0.2708
67	42	0.8750
68	47	0.9792
69	28	0.5833
70	33	0.6875
71	14	0.2917
72	19	0.3958
73	0	0.0000
74	5	0.1042
75	34	0.7083
76	39	0.8125
77	20	0.4167
78	25	0.5208
79	6	0.1250
80	11	0.2292
81	40	0.8333
82	45	0.9375
83	26	0.5417
84	31	0.6458
85	12	0.2500
86	17	0.3542
87	46	0.9583
88	3	0.0625
89	32	0.6667
90	37	0.7708
91	18	0.3750
92	23	0.4792
93	4	0.0833
94	9	0.1875
95	38	0.7917
96	43	0.8958
97	24	0.5000
98	29	0.6042
99	10	0.2083
100	15	0.3125

In [5]:
N = 100

a = 16807
c = 0
m = 2**31 - 1
x0 = 13

[I,X,U] = genranN(a,c,m,x0,N)
showValues(I,X,U)

i	Xi	Ui
1	218491	0.0001
2	1524694590	0.7100
3	1767098126	0.8229
4	2066849319	0.9625
5	1988514208	0.9260
6	1817779242	0.8465
7	1313358072	0.6116
8	1772192238	0.8252
9	1784243823	0.8309
10	324286453	0.1510
11	2116403132	0.9855
12	1615794263	0.7524
13	1723461926	0.8025
14	965159546	0.4494
15	1492503831	0.6950
16	1902890657	0.8861
17	1556801075	0.7249
18	214912477	0.1001
19	2113990332	0.9844
20	1866053956	0.8689
21	917657704	0.4273
22	1992962021	0.9280
23	1410244688	0.6567
24	205459277	0.0957
25	364163	0.0002
26	1825520247	0.8501
27	419926640	0.1955
28	1075774438	0.5009
29	876155373	0.4080
30	247986532	0.1155
31	1791368144	0.8342
32	1951148915	0.9086
33	884524715	0.4119
34	1325080471	0.6170
35	1222056707	0.5691
36	573474641	0.2670
37	481683551	0.2243
38	1789576114	0.8333
39	1897271763	0.8835
40	1609330085	0.7494
41	454204630	0.2115
42	1660334972	0.7732
43	847365286	0.3946
44	1704298545	0.7936
45	1008762129	0.4697
46	2029192685	0.9449
47	453658788	0.2113
48	1076303066	0.5012
49	1170871581	0.5452
50	1446004406	0.6733
51	2071102190	0.9644
52	452073107	0.2105
53	195566263	0.0911
54	1232202331	0.5738
55	1439769096	0.6704
56	353462076	0.1646
57	697343730	0.3247
58	1437808431	0.6695
59	1760303773	0.8197
60	1690791739	0.7873
61	1633140269	0.7605
62	1200008776	0.5588
63	1528569255	0.7118
64	316599724	0.1474
65	1774567649	0.8263
66	905587207	0.4217
67	987581760	0.4599
68	385532657	0.1795
69	689203200	0.3209
70	2058874129	0.9587
71	1093481992	0.5092
72	2134272165	0.9938
73	1292921314	0.6021
74	1888984052	0.8796
75	1904208363	0.8867
76	81165700	0.0378
77	499804055	0.2327
78	1398208968	0.6511
79	1932059702	0.8997
80	27185227	0.0127
81	1635577025	0.7616
82	1352377575	0.6297
83	442983177	0.2063
84	2039935337	0.9499
85	616784604	0.2872
86	395275359	0.1841
87	1226038542	0.5709
88	924182429	0.4304
89	2132349099	0.9930
90	1184205757	0.5514
91	67717503	0.0315
92	2109223658	0.9822
93	1209458977	0.5632
94	1444307584	0.6726
95	1469902247	0.6845
96	2142673888	0.9978
97	766759073	0.3571
98	2017857911	0.9396
99	1076156753	0.5011
100	859272637	0.4001

In [6]:
N = 100

a = 25214903917
c = 11
m = 2**48
x0 = 29022024

[I,X,U] = genranN(a,c,m,x0,N)
showValues(I,X,U)

i	Xi	Ui
1	234082165873075	0.8316
2	148167533855554	0.5264
3	141807657398053	0.5038
4	3454754934988	0.0123
5	256501397597927	0.9113
6	264449157726822	0.9395
7	11136630401401	0.0396
8	67913613467280	0.2413
9	262619324982107	0.9330
10	188429820514250	0.6694
11	145639627126029	0.5174
12	85824273155220	0.3049
13	167175878175503	0.5939
14	245552656813934	0.8724
15	79047489316321	0.2808
16	196794407487192	0.6992
17	106220417415683	0.3774
18	10128563217746	0.0360
19	31476005146613	0.1118
20	217709941352796	0.7735
21	152714571351095	0.5426
22	99936443708790	0.3550
23	56972566644553	0.2024
24	165707797262368	0.5887
25	48478755519915	0.1722
26	232957411402714	0.8276
27	165084121407453	0.5865
28	19900186500900	0.0707
29	198494058158687	0.7052
30	269746417046654	0.9583
31	210655086898609	0.7484
32	272644017568360	0.9686
33	12082421386835	0.0429
34	127841417489250	0.4542
35	68007552632005	0.2416
36	177087830181356	0.6291
37	183362832420231	0.6514
38	115833433738374	0.4115
39	146529460320537	0.5206
40	269051194639792	0.9559
41	21498384911355	0.0764
42	112375187053546	0.3992
43	125448953517	0.0004
44	172242300534196	0.6119
45	183816026865071	0.6530
46	103262458314126	0.3669
47	179216161966465	0.6367
48	77226761908728	0.2744
49	161972116838051	0.5754
50	44093212317042	0.1567
51	43895151152533	0.1559
52	229298443445884	0.8146
53	210288758065879	0.7471
54	120936949958550	0.4297
55	252810739597033	0.8982
56	190439910022976	0.6766
57	78866111581771	0.2802
58	76051390871546	0.2702
59	15312930042237	0.0544
60	135994243260484	0.4831
61	42602281063679	0.1514
62	139203997944478	0.4946
63	206782395234641	0.7346
64	91339215056264	0.3245
65	92433589015283	0.3284
66	150021564228482	0.5330
67	194282813663845	0.6902
68	21455802518284	0.0762
69	230994743344167	0.8207
70	167085850994342	0.5936
71	248461835835577	0.8827
72	12970372873424	0.0461
73	56140127683739	0.1994
74	269980950755338	0.9592
75	71300276426829	0.2533
76	238122995123924	0.8460
77	143046857515087	0.5082
78	185208642632622	0.6580
79	183211175771425	0.6509
80	138791102672152	0.4931
81	116654277460803	0.4144
82	63867784041874	0.2269
83	181235208739637	0.6439
84	207080736093084	0.7357
85	120220456051063	0.4271
86	231595713489334	0.8228
87	260430597719689	0.9252
88	174020601437792	0.6182
89	267230729596651	0.9494
90	256221856783386	0.9103
91	239239581274909	0.8499
92	141134572171620	0.5014
93	139418143219615	0.4953
94	45910646722750	0.1631
95	218918496752881	0.7778
96	158251995246760	0.5622
97	45004150646675	0.1599
98	272135688711074	0.9668
99	244405838503941	0.8683
100	42871525498924	0.1523

In [7]:
N = 100

a = 5
c = 7
m = 200
x0 = 3

[I,X,U] = genranN(a,c,m,x0,N)
showValues(I,X,U)

i	Xi	Ui
1	22	0.1100
2	117	0.5850
3	192	0.9600
4	167	0.8350
5	42	0.2100
6	17	0.0850
7	92	0.4600
8	67	0.3350
9	142	0.7100
10	117	0.5850
11	192	0.9600
12	167	0.8350
13	42	0.2100
14	17	0.0850
15	92	0.4600
16	67	0.3350
17	142	0.7100
18	117	0.5850
19	192	0.9600
20	167	0.8350
21	42	0.2100
22	17	0.0850
23	92	0.4600
24	67	0.3350
25	142	0.7100
26	117	0.5850
27	192	0.9600
28	167	0.8350
29	42	0.2100
30	17	0.0850
31	92	0.4600
32	67	0.3350
33	142	0.7100
34	117	0.5850
35	192	0.9600
36	167	0.8350
37	42	0.2100
38	17	0.0850
39	92	0.4600
40	67	0.3350
41	142	0.7100
42	117	0.5850
43	192	0.9600
44	167	0.8350
45	42	0.2100
46	17	0.0850
47	92	0.4600
48	67	0.3350
49	142	0.7100
50	117	0.5850
51	192	0.9600
52	167	0.8350
53	42	0.2100
54	17	0.0850
55	92	0.4600
56	67	0.3350
57	142	0.7100
58	117	0.5850
59	192	0.9600
60	167	0.8350
61	42	0.2100
62	17	0.0850
63	92	0.4600
64	67	0.3350
65	142	0.7100
66	117	0.5850
67	192	0.9600
68	167	0.8350
69	42	0.2100
70	17	0.0850
71	92	0.4600
72	67	0.3350
73	142	0.7100
74	117	0.5850
75	192	0.9600
76	167	0.8350
77	42	0.2100
78	17	0.0850
79	92	0.4600
80	67	0.3350
81	142	0.7100
82	117	0.5850
83	192	0.9600
84	167	0.8350
85	42	0.2100
86	17	0.0850
87	92	0.4600
88	67	0.3350
89	142	0.7100
90	117	0.5850
91	192	0.9600
92	167	0.8350
93	42	0.2100
94	17	0.0850
95	92	0.4600
96	67	0.3350
97	142	0.7100
98	117	0.5850
99	192	0.9600
100	167	0.8350

In [8]:
import numpy as np
import pandas as pd

# visualizar las 100 iteraciones (para evitar q se omitan iteriaciones mostrando puntos suspesivos)
pd.set_option("display.max_rows", 100)
pd.set_option("display.min_rows", 100)


# 1. shift-register (

def shift_register_generator(seed_bits, tap_indices, b=31, n=100):
    """
    genera n numeros pseudoaleatorios en [0, 1) usando Feedback Shift-Register.
    """
    bits = list(seed_bits)
    sequence_u = []

    for _ in range(n):
        # generar b bits consecutivos con la suma mód 2
        for _ in range(b):
            next_bit = sum(bits[-idx] for idx in tap_indices) % 2
            bits.append(next_bit)

        # empaquetar los ultimos b bits en un entero
        val = 0
        for bit in bits[-b:]:
            val = (val << 1) | bit

        sequence_u.append(val / (2**b))

    return sequence_u



# 2. lagged-fibonacci

def lagged_fibonacci_generator(seed_table, j=3, k=7, m=31, op="+", n=100):
    """
    Genera n numeros pseudoaleatorios en [0, 1) usando Lagged-Fibonacci.
    """
    M = 2**m
    table = list(seed_table)
    sequence_u = []

    for i in range(k, k + n):
        if op == "+":
            val = (table[i - j] + table[i - k]) % M
        elif op == "-":
            val = (table[i - j] - table[i - k]) % M
        elif op == "*":
            val = (table[i - j] * table[i - k]) % M
        elif op == "^":
            val = (table[i - j] ^ table[i - k]) % M

        table.append(val)
        sequence_u.append(val / M)

    return sequence_u



# ejecuion


# Parámetros Shift-Register (k=31 bits, taps en 31 y 3)
seed_bits_sr = [
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    1,
    0,
    1,
]
taps_sr = [31, 3]
u_shift = shift_register_generator(seed_bits_sr, taps_sr, b=31, n=100)

# Parámetros Lagged-Fibonacci (k=7, j=3, m=31 -> M=2^31, op='+')
seeds_lfg = [123456789 * i + 987654321 for i in range(1, 8)]
u_fibonacci = lagged_fibonacci_generator(
    seeds_lfg, j=3, k=7, m=31, op="+", n=100
)

# Tabla final con las 100 iteraciones exactas
df_resultado = pd.DataFrame(
    {"Shift-Register": u_shift, "Lagged-Fibonacci": u_fibonacci}
)

df_resultado.index = range(1, 101)
df_resultado.index.name = "Iteración (i)"

# Visualizar la tabla de 100 elementos
display(df_resultado)

               Shift-Register  Lagged-Fibonacci
Iteración (i)
1                    0.066357          0.264759
2                    0.357626          0.379737
3                    0.319246          0.494715
4                    0.644913          0.954628
5                    0.022164          0.127095
6                    0.868660          0.299562
7                    0.332022          0.816963
8                    0.802091          0.391854
9                    0.726916          0.679299
10                   0.312828          0.311679
11                   0.357343          0.346481
12                   0.095525          0.806394
13                   0.248120          0.611240
14                   0.109440          0.163445
15                   0.339351          0.198248
16                   0.634986          0.290540
17                   0.988939          0.475123
18                   0.771852          0.544729
19                   0.591656          0.096933
20                   0.637028          0.086364
21                   0.709477          0.708174
22                   0.797437          0.295181
23                   0.268349          0.376903
24                   0.983581          0.183297
25                   0.096951          0.839910
26                   0.677705          0.473837
27                   0.157960          0.269661
28                   0.605747          0.548084
29                   0.236359          0.769018
30                   0.551374          0.646564
31                   0.843223          0.731381
32                   0.083787          0.608928
33                   0.630250          0.120401
34                   0.005719          0.001042
35                   0.574528          0.157011
36                   0.067169          0.889419
37                   0.646519          0.647606
38                   0.296906          0.888392
39                   0.839251          0.498346
40                   0.476160          0.768007
41                   0.326530          0.889434
42                   0.792216          0.655358
43                   0.954199          0.657426
44                   0.195415          0.537041
45                   0.651811          0.543750
46                   0.134957          0.155772
47                   0.564932          0.305048
48                   0.212248          0.433185
49                   0.474526          0.811130
50                   0.466979          0.962474
51                   0.194282          0.970225
52                   0.922777          0.354880
53                   0.731709          0.118246
54                   0.539357          0.275273
55                   0.598479          0.788065
56                   0.674344          0.929376
57                   0.162409          0.237747
58                   0.743541          0.758290
59                   0.116763          0.284256
60                   0.117679          0.355993
61                   0.669084          0.033563
62                   0.182043          0.072320
63                   0.828514          0.285368
64                   0.625400          0.271310
65                   0.142751          0.830610
66                   0.984221          0.569624
67                   0.902695          0.627303
68                   0.584525          0.864173
69                   0.480422          0.641944
70                   0.315932          0.912671
71                   0.642292          0.135483
72                   0.588776          0.472554
73                   0.474784          0.482295
74                   0.243211          0.762785
75                   0.775652          0.336727
76                   0.864133          0.124240
77                   0.879234          0.675456
78                   0.853007          0.472210
79                   0.543848          0.596794
80                   0.040885          0.157752
81                   0.258566          0.234995
82                   0.152050          0.933521
83                   0.691202          0.281991
84                   0.642535          0.910451
85                   0.873240          0.405731
86                   0.109574          0.878785
87                   0.553624          0.068203
88                   0.841069          0.640726
89                   0.914338          0.812306
90                   0.187255          0.350194
91                   0.277561          0.551177
92                   0.138221          0.218037
93                   0.432448          0.228979
94                   0.275324          0.619381
95                   0.689289          0.858763
96                   0.928904          0.041285
97                   0.047915          0.969575
98                   0.054615          0.409940
99                   0.729226          0.259322
100                  0.453795          0.198554

## Análisis adicional: Periodo, Prueba de Uniformidad (Chi-cuadrada) y Prueba de Aleatoriedad (Rachas)

A continuación se aplican tres análisis a **todas** las secuencias generadas arriba (Cuadrados Medios, los 5 Generadores Congruenciales Lineales, Shift-Register y Lagged-Fibonacci):

- **a. Periodo o ciclo**: se busca la primera repetición de un valor ya generado; el periodo es la distancia entre esa repetición y su primera aparición. Si no se detecta repetición dentro de las N observaciones generadas, se reporta como `>N` (el periodo real es mayor o igual a N).
- **b. Prueba de uniformidad (Chi-cuadrada)**: se divide `[0,1)` en `k` intervalos, se compara la frecuencia observada `Oi` contra la esperada `Ei = n/k`, y se calcula `χ² = Σ (Oi - Ei)² / Ei`, comparándolo contra el valor crítico `χ²_(k-1, 1-α)`.
- **c. Prueba de aleatoriedad (Rachas arriba/abajo de la media)**: se codifica cada `u_i` como `+` si está por encima de la media (0.5) o `-` si está por debajo, se cuenta el número de rachas `R` y se compara el estadístico `Z = (R - μ_R) / σ_R` contra el valor crítico normal `Z_(1-α/2)`.

In [9]:
import numpy as np
from scipy import stats


def encontrar_periodo(secuencia):
  """
  a. busca la primera vez que un valor ya visto se repite; el periodo
  es la distancia entre la posición actual y la primera aparición
  de ese valor.
  """
  vistos = {}
  for i, val in enumerate(secuencia):
    if val in vistos:
      inicio = vistos[val]
      return {
          "tiene_ciclo": True,
          "inicio_ciclo": inicio,
          "periodo": i - inicio,
          "n_evaluado": len(secuencia),
      }
    vistos[val] = i
  return {
      "tiene_ciclo": False,
      "inicio_ciclo": None,
      "periodo": None,
      "n_evaluado": len(secuencia),
  }


def prueba_chi_cuadrada(u, k=10, alpha=0.05):
  """
  b. prueba de uniformidad Chi-cuadrada.
  H0: los Ui provienen de una distribución U(0,1).
  """
  n = len(u)
  limites = np.linspace(0, 1, k + 1)
  obs, _ = np.histogram(u, bins=limites)
  esperado = n / k
  estadistico = np.sum((obs - esperado) ** 2 / esperado)
  gl = k - 1
  valor_critico = stats.chi2.ppf(1 - alpha, gl)
  p_valor = 1 - stats.chi2.cdf(estadistico, gl)
  pasa = estadistico <= valor_critico
  return {
      "n": n, "k": k,
      "chi2_calculado": estadistico,
      "chi2_critico": valor_critico,
      "gl": gl,
      "p_valor": p_valor,
      "conclusion": "No se rechaza H0 (uniforme)" if pasa else "Se rechaza H0 (NO uniforme)",
  }


def prueba_rachas(u, alpha=0.05):
  """
  c. prueba de rachas arriba/abajo de la media, para independencia (aleatoriedad).
  H0: la secuencia es aleatoria (independiente).
  """
  u = np.asarray(u, dtype=float)
  media = np.mean(u)
  signos = np.where(u > media, 1, 0)

  rachas = 1
  for i in range(1, len(signos)):
    if signos[i] != signos[i - 1]:
      rachas += 1

  n1 = int(np.sum(signos == 1))
  n2 = int(np.sum(signos == 0))
  n = n1 + n2

  mu_r = 2 * n1 * n2 / n + 1
  var_r = (2 * n1 * n2 * (2 * n1 * n2 - n)) / (n**2 * (n - 1))
  z = 0.0 if var_r <= 0 else (rachas - mu_r) / np.sqrt(var_r)
  z_critico = stats.norm.ppf(1 - alpha / 2)
  p_valor = 2 * (1 - stats.norm.cdf(abs(z)))
  pasa = abs(z) <= z_critico

  return {
      "n1": n1, "n2": n2,
      "rachas_obs": rachas,
      "rachas_esperadas": mu_r,
      "varianza": var_r,
      "z_calculado": z,
      "z_critico": z_critico,
      "p_valor": p_valor,
      "conclusion": "No se rechaza H0 (aleatoria)" if pasa else "Se rechaza H0 (NO aleatoria)",
  }

### Aplicacion al metodo Midsquare

In [10]:
filas_ms = []
for s, df in results.items():
  per = encontrar_periodo(df["X_i"].tolist())
  chi = prueba_chi_cuadrada(df["u_i"].tolist(), k=10)
  rac = prueba_rachas(df["u_i"].tolist())
  filas_ms.append({
      "Semilla": s,
      "Periodo": per["periodo"] if per["tiene_ciclo"] else f">{per['n_evaluado']}",
      "Chi2 calc": round(chi["chi2_calculado"], 3),
      "Chi2 crit": round(chi["chi2_critico"], 3),
      "Uniforme?": chi["conclusion"],
      "Z rachas": round(rac["z_calculado"], 3),
      "Z crit": round(rac["z_critico"], 3),
      "Aleatoria?": rac["conclusion"],
  })

df_ms = pd.DataFrame(filas_ms)
print("== Cuadrados Medios: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==")
print(df_ms.to_string(index=False))
df_ms

== Cuadrados Medios: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==
 Semilla Periodo  Chi2 calc  Chi2 crit                   Uniforme?  Z rachas  Z crit                   Aleatoria?
    1931       1      860.6     16.919 Se rechaza H0 (NO uniforme)    -8.587    1.96 Se rechaza H0 (NO aleatoria)
  675248    >100       12.4     16.919 No se rechaza H0 (uniforme)     1.608    1.96 No se rechaza H0 (aleatoria)
    4567       4      109.4     16.919 Se rechaza H0 (NO uniforme)    -0.402    1.96 No se rechaza H0 (aleatoria)
   12122       1       52.2     16.919 Se rechaza H0 (NO uniforme)    -3.407    1.96 Se rechaza H0 (NO aleatoria)
 7179345    >100       15.0     16.919 No se rechaza H0 (uniforme)    -1.149    1.96 No se rechaza H0 (aleatoria)

,Semilla,Periodo,Chi2 calc,Chi2 crit,Uniforme?,Z rachas,Z crit,Aleatoria?
0,1931,1,860.6,16.919,Se rechaza H0 (NO uniforme),-8.587,1.96,Se rechaza H0 (NO aleatoria)
1,675248,>100,12.4,16.919,No se rechaza H0 (uniforme),1.608,1.96,No se rechaza H0 (aleatoria)
2,4567,4,109.4,16.919,Se rechaza H0 (NO uniforme),-0.402,1.96,No se rechaza H0 (aleatoria)
3,12122,1,52.2,16.919,Se rechaza H0 (NO uniforme),-3.407,1.96,Se rechaza H0 (NO aleatoria)
4,7179345,>100,15.0,16.919,No se rechaza H0 (uniforme),-1.149,1.96,No se rechaza H0 (aleatoria)

### Aplicado a los 5 Generadores Congruenciales Lineales

In [11]:
lcg_params = [
    {"nombre": "LCG 1 (a=115, c=0, m=128, x0=127)",              "a": 115,           "c": 0,  "m": 128,      "x0": 127},
    {"nombre": "LCG 2 (a=25, c=5, m=48, x0=43)",                 "a": 25,            "c": 5,  "m": 48,       "x0": 43},
    {"nombre": "LCG 3 (a=16807, c=0, m=2^31-1, x0=13)",          "a": 16807,         "c": 0,  "m": 2**31-1,  "x0": 13},
    {"nombre": "LCG 4 (a=25214903917, c=11, m=2^48, x0=29022024)","a": 25214903917,  "c": 11, "m": 2**48,    "x0": 29022024},
    {"nombre": "LCG 5 (a=5, c=7, m=200, x0=3)",                  "a": 5,             "c": 7,  "m": 200,      "x0": 3},
]

filas_lcg = []
for p in lcg_params:
  I, X, U = genranN(p["a"], p["c"], p["m"], p["x0"], 100)
  per = encontrar_periodo(X)
  chi = prueba_chi_cuadrada(U, k=10)
  rac = prueba_rachas(U)
  filas_lcg.append({
      "Generador": p["nombre"],
      "Periodo": per["periodo"] if per["tiene_ciclo"] else f">{per['n_evaluado']}",
      "Chi2 calc": round(chi["chi2_calculado"], 3),
      "Chi2 crit": round(chi["chi2_critico"], 3),
      "Uniforme?": chi["conclusion"],
      "Z rachas": round(rac["z_calculado"], 3),
      "Z crit": round(rac["z_critico"], 3),
      "Aleatoria?": rac["conclusion"],
  })

df_lcg = pd.DataFrame(filas_lcg)
print("== Generadores Congruenciales Lineales: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==")
print(df_lcg.to_string(index=False))
df_lcg

== Generadores Congruenciales Lineales: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==
                                       Generador Periodo  Chi2 calc  Chi2 crit                   Uniforme?  Z rachas  Z crit                   Aleatoria?
               LCG 1 (a=115, c=0, m=128, x0=127)      32        6.8     16.919 No se rechaza H0 (uniforme)    -1.005    1.96 No se rechaza H0 (aleatoria)
                  LCG 2 (a=25, c=5, m=48, x0=43)      48        1.2     16.919 No se rechaza H0 (uniforme)    -1.005    1.96 No se rechaza H0 (aleatoria)
           LCG 3 (a=16807, c=0, m=2^31-1, x0=13)    >100       12.0     16.919 No se rechaza H0 (uniforme)     0.440    1.96 No se rechaza H0 (aleatoria)
LCG 4 (a=25214903917, c=11, m=2^48, x0=29022024)    >100        4.8     16.919 No se rechaza H0 (uniforme)     0.217    1.96 No se rechaza H0 (aleatoria)
                   LCG 5 (a=5, c=7, m=200, x0=3)       8       22.8     16.919 Se rechaza H0 (NO uniforme)    -5.023    1.96 Se rechaza H0 (NO aleatoria)

,Generador,Periodo,Chi2 calc,Chi2 crit,Uniforme?,Z rachas,Z crit,Aleatoria?
0,"LCG 1 (a=115, c=0, m=128, x0=127)",32,6.8,16.919,No se rechaza H0 (uniforme),-1.005,1.96,No se rechaza H0 (aleatoria)
1,"LCG 2 (a=25, c=5, m=48, x0=43)",48,1.2,16.919,No se rechaza H0 (uniforme),-1.005,1.96,No se rechaza H0 (aleatoria)
2,"LCG 3 (a=16807, c=0, m=2^31-1, x0=13)",>100,12.0,16.919,No se rechaza H0 (uniforme),0.440,1.96,No se rechaza H0 (aleatoria)
3,"LCG 4 (a=25214903917, c=11, m=2^48, x0=29022024)",>100,4.8,16.919,No se rechaza H0 (uniforme),0.217,1.96,No se rechaza H0 (aleatoria)
4,"LCG 5 (a=5, c=7, m=200, x0=3)",8,22.8,16.919,Se rechaza H0 (NO uniforme),-5.023,1.96,Se rechaza H0 (NO aleatoria)

### Aplicado a Shift-Register y Lagged-Fibonacci

In [14]:
filas_sf = []
for nombre, u in [("Shift-Register", u_shift), ("Lagged-Fibonacci", u_fibonacci)]:
  per = encontrar_periodo(u)
  chi = prueba_chi_cuadrada(u, k=10)
  rac = prueba_rachas(u)
  filas_sf.append({
      "Generador": nombre,
      "Periodo": per["periodo"] if per["tiene_ciclo"] else f">{per['n_evaluado']}",
      "Chi2 calc": round(chi["chi2_calculado"], 3),
      "Chi2 crit": round(chi["chi2_critico"], 3),
      "Uniforme?": chi["conclusion"],
      "Z rachas": round(rac["z_calculado"], 3),
      "Z crit": round(rac["z_critico"], 3),
      "Aleatoria?": rac["conclusion"],
  })

df_sf = pd.DataFrame(filas_sf)
print("== Shift-Register / Lagged-Fibonacci: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==")
print(df_sf.to_string(index=False))
df_sf

== Shift-Register / Lagged-Fibonacci: Periodo, Uniformidad (Chi2) y Aleatoriedad (Rachas) ==
       Generador Periodo  Chi2 calc  Chi2 crit                   Uniforme?  Z rachas  Z crit                   Aleatoria?
  Shift-Register    >100        6.0     16.919 No se rechaza H0 (uniforme)     0.419    1.96 No se rechaza H0 (aleatoria)
Lagged-Fibonacci    >100        6.8     16.919 No se rechaza H0 (uniforme)    -0.789    1.96 No se rechaza H0 (aleatoria)

,Generador,Periodo,Chi2 calc,Chi2 crit,Uniforme?,Z rachas,Z crit,Aleatoria?
0,Shift-Register,>100,6.0,16.919,No se rechaza H0 (uniforme),0.419,1.96,No se rechaza H0 (aleatoria)
1,Lagged-Fibonacci,>100,6.8,16.919,No se rechaza H0 (uniforme),-0.789,1.96,No se rechaza H0 (aleatoria)

### Resumen general de todos los generadores

In [13]:
df_ms_r = df_ms.rename(columns={"Semilla": "Generador"}).copy()
df_ms_r["Generador"] = "Cuadrados Medios (semilla=" + df_ms_r["Generador"].astype(str) + ")"

df_resumen_general = pd.concat([df_ms_r, df_lcg, df_sf], ignore_index=True)
df_resumen_general

,Generador,Periodo,Chi2 calc,Chi2 crit,Uniforme?,Z rachas,Z crit,Aleatoria?
0,Cuadrados Medios (semilla=1931),1,860.6,16.919,Se rechaza H0 (NO uniforme),-8.587,1.96,Se rechaza H0 (NO aleatoria)
1,Cuadrados Medios (semilla=675248),>100,12.4,16.919,No se rechaza H0 (uniforme),1.608,1.96,No se rechaza H0 (aleatoria)
2,Cuadrados Medios (semilla=4567),4,109.4,16.919,Se rechaza H0 (NO uniforme),-0.402,1.96,No se rechaza H0 (aleatoria)
3,Cuadrados Medios (semilla=12122),1,52.2,16.919,Se rechaza H0 (NO uniforme),-3.407,1.96,Se rechaza H0 (NO aleatoria)
4,Cuadrados Medios (semilla=7179345),>100,15.0,16.919,No se rechaza H0 (uniforme),-1.149,1.96,No se rechaza H0 (aleatoria)
5,"LCG 1 (a=115, c=0, m=128, x0=127)",32,6.8,16.919,No se rechaza H0 (uniforme),-1.005,1.96,No se rechaza H0 (aleatoria)
6,"LCG 2 (a=25, c=5, m=48, x0=43)",48,1.2,16.919,No se rechaza H0 (uniforme),-1.005,1.96,No se rechaza H0 (aleatoria)
7,"LCG 3 (a=16807, c=0, m=2^31-1, x0=13)",>100,12.0,16.919,No se rechaza H0 (uniforme),0.440,1.96,No se rechaza H0 (aleatoria)
8,"LCG 4 (a=25214903917, c=11, m=2^48, x0=29022024)",>100,4.8,16.919,No se rechaza H0 (uniforme),0.217,1.96,No se rechaza H0 (aleatoria)
9,"LCG 5 (a=5, c=7, m=200, x0=3)",8,22.8,16.919,Se rechaza H0 (NO uniforme),-5.023,1.96,Se rechaza H0 (NO aleatoria)
10,Shift-Register,>100,6.0,16.919,No se rechaza H0 (uniforme),0.419,1.96,No se rechaza H0 (aleatoria)
11,Lagged-Fibonacci,>100,6.8,16.919,No se rechaza H0 (uniforme),-0.789,1.96,No se rechaza H0 (aleatoria)

# ¿Cuáles son los peores generadores de números aleatorios y porqué?
el peor generador es el Midsquare ya que este generador muestra periodos muy cortos (1, 4, 8), lo que significa que comienzan a repetir secuencias demasiado rapido, haciendolos inadecuados para generar numeros verdaderamente aleatorios. Tambien fallan consistentemente la prueba de uniformidad ('Se rechaza H0 (NO uniforme)') y/o la prueba de aleatoriedad ('Se rechaza H0 (NO aleatoria)'), indicando que sus salidas no están distribuidas uniformemente ni son suficientemente aleatorias. Por ejemplo, 'Cuadrados Medios (semilla=1931)' y 'LCG 5' tienen valores de 'Chi2 calc' muy altos en comparación con 'Chi2 crit', y valores absolutos de 'Z rachas' altos, lo que confirma su bajo rendimiento.

#¿Cuáles son los mejores generadores de números aleatorios y porqué?

1. LCG  (a=25214903917, c=11, m=2^48, x0=29022024)
- Justificación: Este generador es el más robusto de todos los analizados. Pasó las pruebas de uniformidad y aleatoriedad, y su periodo es mayor a 100 iteraciones (>100). Su módulo extremadamente grande (m=2^48) implica que su periodo real es inmensamente largo, lo que lo hace ideal para aplicaciones que requieren secuencias muy extensas de números aleatorios de alta calidad. Su diseño es algorítmicamente superior.
2. Shift-Register
- Justificación: Este generador también pasó las pruebas de uniformidad y aleatoriedad con un periodo >100. Los generadores de registro de desplazamiento son conocidos por su eficiencia y capacidad de producir secuencias con muy buenas propiedades de aleatoriedad y periodos largos, dependiendo de la configuración de bits y los 'taps'.